
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * The ChangePasswordFrame class represents the graphical user interface for changing the customer's password.
 * It extends JFrame and provides a form to enter the old and new passwords along with buttons to confirm the password change or go back.
 */

public class ChangePasswordFrame extends javax.swing.JFrame {

        /** The customer associated with the change password frame. */
    customer cs = null;

    /**
     * Creates a new instance of ChangePasswordFrame.
     *
     * @param obj The customer object associated with the change password frame.
     */
    public ChangePasswordFrame(customer obj) {
        cs = obj;
        initComponents();
        ImageIcon background_img = new ImageIcon("/Users/waniya_mustafa/Desktop/SMMS_Images/Changepss.jpeg", "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(800, 550, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 800, 550);
        this.add(backgrnd);
        this.setTitle("Change Password");
        this.setResizable(false);
        backBtn.setOpaque(true);
        changeBtn.setOpaque(true);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);

    }

    /**
     * Initializes the graphical user interface components. This method is auto-generated by the NetBeans Form Editor.
     * It sets up the layout, labels, text fields, and buttons for changing the password.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newPassField = new javax.swing.JPasswordField();
        backBtn = new javax.swing.JButton();
        oldPassField = new javax.swing.JPasswordField();
        changeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hubballi", 1, 26)); // NOI18N
        jLabel1.setText("Enter Old Password:");

        jLabel3.setFont(new java.awt.Font("Hubballi", 1, 24)); // NOI18N
        jLabel3.setText("Enter New Password:");

        newPassField.setBackground(new java.awt.Color(204, 204, 204));
        newPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassFieldActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 102, 102));
        backBtn.setFont(new java.awt.Font("Hoefler Text", 1, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        oldPassField.setBackground(new java.awt.Color(204, 204, 204));
        oldPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPassFieldActionPerformed(evt);
            }
        });

        changeBtn.setBackground(new java.awt.Color(255, 102, 102));
        changeBtn.setFont(new java.awt.Font("Hoefler Text", 1, 18)); // NOI18N
        changeBtn.setText("Change Password");
        changeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        changeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(newPassField,
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel3,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(oldPassField,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 208,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(changeBtn,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(525, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(oldPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(changeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141,
                                        Short.MAX_VALUE)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler for the "Back" button. Closes the current change password window.
     *
     * @param evt The ActionEvent triggered by the button.
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
    }// GEN-LAST:event_backBtnActionPerformed

    /**
 * This method is called when an action event occurs in the new password field.
 * Currently, it does not contain any specific handling code.
 *
 * @param evt The ActionEvent triggered by an action in the new password field.
 */
    private void newPassFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_newPassFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_newPassFieldActionPerformed

    /**         
* This method is called when an action event occurs in the old password field.
 * Currently, it does not contain any specific handling code.
 *
 * @param evt The ActionEvent triggered by an action in the old password field.
 */
    private void oldPassFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_oldPassFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_oldPassFieldActionPerformed

    /**
     * Event handler for the "Change Password" button. Changes the customer's password if the entered old password matches.
     *
     * @param evt The ActionEvent triggered by the button.
     */
    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_changeBtnActionPerformed
        if (oldPassField.getText().length() != 0 && newPassField.getText().length() != 0) {
            if (oldPassField.getText().equals(cs.getPassword())) {
                cs.setPassword(newPassField.getText());
                JOptionPane.showMessageDialog(this, "Password Changed successfully! ", "Alert",
                        JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(this, "Wrong Old Password!\n Try Again! ", "ERROR",
                        JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(this, "New or Old password can not be empty! ", "ERROR",
                    JOptionPane.ERROR_MESSAGE);

        }
    }// GEN-LAST:event_changeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton changeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField newPassField;
    private javax.swing.JPasswordField oldPassField;
    // End of variables declaration//GEN-END:variables
}
