/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystexm/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class MenuFrame extends javax.swing.JFrame {

    ArrayList<Product> products;
    customer obj = null;

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame(customer obj) {

        this.obj = obj;
        initComponents();
        ImageIcon background_img = new ImageIcon(
                "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SMMS_Images\\Menu.png", "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(1200, 820, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 1200, 820);
        this.add(backgrnd);
        this.setTitle("User Menu");
        this.setResizable(false);
        showCartBtn.setOpaque(true);
        showCatBtn.setOpaque(true);
        showDetailsBtn.setOpaque(true);
        showPrevOrdersBtn.setOpaque(true);
        logoutBtn.setOpaque(true);
        changePssBtn.setOpaque(true);
        this.setLocationRelativeTo(null);

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showCatBtn = new javax.swing.JButton();
        showDetailsBtn = new javax.swing.JButton();
        showCartBtn = new javax.swing.JButton();
        showPrevOrdersBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        changePssBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showCatBtn.setBackground(new java.awt.Color(255, 102, 102));
        showCatBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        showCatBtn.setText("Categories");
        showCatBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showCatBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCatBtnActionPerformed(evt);
            }
        });

        showDetailsBtn.setBackground(new java.awt.Color(255, 102, 102));
        showDetailsBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        showDetailsBtn.setText("View Details");
        showDetailsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showDetailsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsBtnActionPerformed(evt);
            }
        });

        showCartBtn.setBackground(new java.awt.Color(255, 102, 102));
        showCartBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        showCartBtn.setText("Cart");
        showCartBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showCartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCartBtnActionPerformed(evt);
            }
        });

        showPrevOrdersBtn.setBackground(new java.awt.Color(255, 102, 102));
        showPrevOrdersBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        showPrevOrdersBtn.setText("View Orders");
        showPrevOrdersBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showPrevOrdersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPrevOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPrevOrdersBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(255, 102, 102));
        logoutBtn.setFont(new java.awt.Font("Hoefler Text", 1, 26)); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        changePssBtn.setBackground(new java.awt.Color(255, 102, 102));
        changePssBtn.setFont(new java.awt.Font("Hoefler Text", 1, 25)); // NOI18N
        changePssBtn.setText("Change Password");
        changePssBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        changePssBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePssBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePssBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(changePssBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(showCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(showPrevOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(showCatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        305, Short.MAX_VALUE)
                                                .addComponent(showDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(216, 216, 216)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(showCatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(showCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showPrevOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(166, 166, 166)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(changePssBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(157, 157, 157)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showDetailsBtnActionPerformed
        UserInfoFrame obj1 = new UserInfoFrame(obj);
        obj1.setVisible(true);

    }// GEN-LAST:event_showDetailsBtnActionPerformed

    private void changePssBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_changePssBtnActionPerformed
        ChangePasswordFrame object = new ChangePasswordFrame(obj);
        object.setVisible(true);

    }// GEN-LAST:event_changePssBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        String info = obj.getID() + "," + obj.getName() + "," + obj.getPassword() + "," + obj.getAddress() + ","
                + obj.getPhoneNumber() + "," + obj.getGender();

        try {
            FileWriter myWriter = new FileWriter(
                    "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                            + obj.getID() + ".txt");

            myWriter.write(info);
            myWriter.close();
            this.setVisible(false);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
        try {
            FileWriter myWriter = new FileWriter(
                    "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                            + obj.getID()
                            + "_orders.txt");
            ArrayList<order> or = obj.getOrders();
            for (int i = 0; i < or.size(); i++) {
                myWriter.write(or.get(i).toString() + "\n");

            }
            myWriter.close();
            JOptionPane.showMessageDialog(this, "Logged Out Successfully!", "ALERT", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

    }// GEN-LAST:event_logoutBtnActionPerformed

    private void showCatBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showCatBtnActionPerformed
        String line;

        products = new ArrayList<>();
        File myObj = new File(
                "C:\\Users\\DELL\\Desktop\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\productsDetails.txt");
        Scanner myReader;
        try {
            myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                line = myReader.nextLine();
                String[] res = line.split("[,]", 0);
                if (res[1].equals("EL")) {
                    Product el = new Electronics(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(el);
                } else if (res[1].equals("KA")) {
                    Product ka = new kitchen(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(ka);
                } else if (res[1].equals("Dairy")) {
                    Product dairy = new Dairy(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(dairy);
                } else if (res[1].equals("COS")) {
                    Product cos = new Cosmetics(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(cos);
                } else if (res[1].equals("FG")) {
                    Product fg = new FruitAndVegitables(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(fg);
                } else if (res[1].equals("HE")) {
                    Product he = new Households(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(he);
                }

            }
            CategoriesFrame object = new CategoriesFrame(obj, products);
            object.setVisible(true);

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

    }// GEN-LAST:event_showCatBtnActionPerformed

    private void showPrevOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showPrevOrdersBtnActionPerformed
        // TODO add your handling code here:
        if (obj.getOrders().isEmpty()) {
            JOptionPane.showMessageDialog(this, "You have NO previous orders!", "ALERT",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {
            PrevOrdersFrame obj1 = new PrevOrdersFrame(obj);
            obj1.setVisible(true);

        }

    }// GEN-LAST:event_showPrevOrdersBtnActionPerformed

    private void showCartBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showCartBtnActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        ArrayList<order> ors = obj.getOrders();
        for (int j = 0; j < ors.size(); j++) {
            if (ors.get(j).getType().equals("curr")) {
                flag = true;
                break;
            }
        }
        if (!flag) {
            JOptionPane.showMessageDialog(this, "Your Cart is Empty!", "ALERT", JOptionPane.INFORMATION_MESSAGE);

        } else {
            CartFrame obj1 = new CartFrame(obj, products);
            obj1.setVisible(true);
        }

    }// GEN-LAST:event_showCartBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePssBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton showCartBtn;
    private javax.swing.JButton showCatBtn;
    private javax.swing.JButton showDetailsBtn;
    private javax.swing.JButton showPrevOrdersBtn;
    // End of variables declaration//GEN-END:variables
}
