
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;

import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class CartFrame extends javax.swing.JFrame {

    ArrayList<Product> pr;
    Customer cs = null;

    /**
     * Creates new form CartFrame
     */
    public CartFrame(Customer cs, ArrayList<Product> pr) {
        this.pr = pr;
        this.cs = cs;
        initComponents();
        ImageIcon background_img = new ImageIcon(
                "C:/Users/MINAHIL SHAKOOR/Downloads/Grocery_Management_System_Java/SMMS_Images/SMMS_Images/ProductsFrame.png", "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(1300, 750, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 1300, 750);
        this.add(backgrnd);
        this.setTitle("Cart");
        this.setResizable(false);
        checkoutBtn.setOpaque(true);
        deleteBtn.setOpaque(true);
        backBtn.setOpaque(true);
        increaseQtyBtn.setOpaque(true);
        this.setLocationRelativeTo(null);

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setLocation(0, 0);

        String[] col = { "ID", "Name", "Quantity", "Price" };
        ArrayList<Order> orders = cs.getOrders();
        DefaultTableModel tableModel = new DefaultTableModel(null, col);
        productsTable.setModel(tableModel);
        productsTable.setAutoResizeMode(JTable.AUTO_RESIZE_NEXT_COLUMN);
        TableColumnModel colModel = productsTable.getColumnModel();
        colModel.getColumn(0).setPreferredWidth(30);
        colModel.getColumn(1).setPreferredWidth(450);
        colModel.getColumn(2).setPreferredWidth(30);
        colModel.getColumn(3).setPreferredWidth(80);
        DefaultCellEditor editor = (DefaultCellEditor) productsTable.getDefaultEditor(Object.class);
        editor.setClickCountToStart(20);
        productsTable.setRowSelectionAllowed(true);
        for (int i = 0; i < orders.size(); i++) {

            if (orders.get(i).getType().equals("curr")) {
                int ID = orders.get(i).getID();
                int qty = orders.get(i).getQuantity();
                double price = orders.get(i).getTotalPrice();
                String data[] = { String.valueOf(ID), orders.get(i).getName(), String.valueOf(qty),
                        String.valueOf(price) };
                tableModel.addRow(data);

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        checkoutBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        increaseQtyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 750));

        productsTable.setBackground(new java.awt.Color(204, 204, 204));
        productsTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        productsTable.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productsTable);
        if (productsTable.getColumnModel().getColumnCount() > 0) {
            productsTable.getColumnModel().getColumn(0).setResizable(false);
            productsTable.getColumnModel().getColumn(1).setResizable(false);
            productsTable.getColumnModel().getColumn(2).setResizable(false);
            productsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        checkoutBtn.setBackground(new java.awt.Color(255, 128, 112));
        checkoutBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        checkoutBtn.setText("Check Out");
        checkoutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        checkoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 128, 112));
        deleteBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 128, 112));
        backBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        increaseQtyBtn.setBackground(new java.awt.Color(255, 128, 112));
        increaseQtyBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        increaseQtyBtn.setText("Increment");
        increaseQtyBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        increaseQtyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        increaseQtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseQtyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(increaseQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(increaseQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
    }// GEN-LAST:event_backBtnActionPerformed

    private void increaseQtyBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_increaseQtyBtnActionPerformed
        // TODO add your handling code here:
        int row = productsTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please Select a Product to increase its Quantity!", "ALERT",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {
            String val = productsTable.getModel().getValueAt(row, 0).toString();
            int ID = Integer.parseInt(val);
            ArrayList<Order> or;
            or = cs.getOrders();
            for (int i = 0; i < or.size(); i++) {
                if (ID == or.get(i).getID() && or.get(i).getType().equals("curr")) {
                    int qty = or.get(i).getQuantity();

                    for (int j = 0; j < pr.size(); j++) {
                        if (ID == pr.get(j).getID()) {
                            double price = pr.get(j).getPrice();
                            if ((qty + 1) <= pr.get(j).getQuantity()) {
                                qty += 1;
                                price = price * qty;
                                Order neworder = new Order(or.get(i).getID(), or.get(i).getName(), qty, price, "curr");
                                or.remove(or.get(i));
                                or.add(neworder);
                                CartFrame main = new CartFrame(cs, pr);
                                main.setVisible(true);
                                this.dispose();
                                break;
                            } else {
                                JOptionPane.showMessageDialog(this, "Product is OUT OF STOCK!", "ALERT",
                                        JOptionPane.INFORMATION_MESSAGE);
                                CartFrame main = new CartFrame(cs, pr);
                                main.setVisible(true);
                                this.dispose();
                                break;

                            }
                        }

                    }
                    break;
                }

            }

        }
    }// GEN-LAST:event_increaseQtyBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_checkoutBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RecieptFrame rf = new RecieptFrame(cs);
        rf.setVisible(true);
    }// GEN-LAST:event_checkoutBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int row = productsTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please Select a Product to show Delete Product!", "ALERT",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {
            String val = productsTable.getModel().getValueAt(row, 0).toString();
            int i = Integer.parseInt(val);
            ArrayList<Order> or;
            or = cs.getOrders();
            for (int j = 0; j < or.size(); j++) {
                if (or.get(j).getID() == i && or.get(j).getType().equals("curr")) {
                    or.remove(or.get(j));
                    cs.setOrders(or);
                    break;

                }
            }

            boolean flag = false;
            ArrayList<Order> ors = cs.getOrders();
            for (int j = 0; j < ors.size(); j++) {
                if (ors.get(j).getType().equals("curr")) {
                    flag = true;
                    break;
                }
            }
            if (!flag) {
                JOptionPane.showMessageDialog(this, "Your Cart is Empty!", "ALERT", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);

            } else {
                CartFrame obj1 = new CartFrame(cs, pr);
                obj1.setVisible(true);
            }

        }
    }// GEN-LAST:event_deleteBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton increaseQtyBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productsTable;
    // End of variables declaration//GEN-END:variables
}
