
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class LoginFrame extends javax.swing.JFrame {

    Customer cs = null;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        ImageIcon background_img = new ImageIcon(
                "C:/Users/MINAHIL SHAKOOR/Downloads/Grocery_Management_System_Java/SMMS_Images/SMMS_Images/LoginFrame.png", "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(1300, 750, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 1300, 750);
        this.add(backgrnd);
        this.setTitle("Login");
        this.setResizable(false);
        loginBtn.setOpaque(true);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setLocation(0, 0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userIDLabel = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        loginHeadingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userIDLabel.setFont(new java.awt.Font("Hubballi", 1, 14)); // NOI18N
        userIDLabel.setText("User ID");

        IDField.setBackground(new java.awt.Color(204, 204, 204));
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(255, 128, 112));
        loginBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        passwordField.setBackground(new java.awt.Color(204, 204, 204));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Hubballi", 1, 14)); // NOI18N
        passwordLabel.setText("Password");

        loginHeadingLabel.setFont(new java.awt.Font("Hubballi", 1, 36)); // NOI18N
        loginHeadingLabel.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(790, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginHeadingLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(loginBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IDField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userIDLabel))
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(loginHeadingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginBtnActionPerformed
        if (IDField.getText().length() != 0 && passwordField.getText().length() != 0) {
            String line = "";
            String ID = IDField.getText();
            ID = ID.trim();
            try {
                File myObj = new File(
                        "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                                + ID + ".txt");
                Scanner myReader = new Scanner(myObj);

                while (myReader.hasNextLine()) {
                    line = myReader.nextLine();

                }
                String[] res = line.split("[,]", 0);
                cs = new Customer(Integer.parseInt(res[0]), res[1], res[4], res[3], res[2], res[5]);
                if (cs.getPassword().equals(passwordField.getText())) {
                    JOptionPane.showMessageDialog(this, "Login Successful!", "ALERT", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    MenuFrame obj = new MenuFrame(cs);
                    obj.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Password! \n Try Again!", "ERROR",
                            JOptionPane.ERROR_MESSAGE);

                }
                myReader.close();
            } catch (FileNotFoundException e) {
                JOptionPane.showMessageDialog(this, "Account with this ID does NOT exist! ", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                this.setVisible(false);
            }
            try {
                ArrayList<Order> orders = new ArrayList<>();
                File myObj = new File(
                        "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                                + ID + "_orders.txt");
                Scanner myReader = new Scanner(myObj);

                while (myReader.hasNextLine()) {
                    if (line.length() > 2) {
                        line = myReader.nextLine();
                        String[] res = line.split("[,]", 0);
                        Order csOrder = new Order(Integer.parseInt(res[0]), res[1], Integer.parseInt(res[2]),
                                Double.valueOf(res[3]), "prev");
                        orders.add(csOrder);
                    }

                }
                cs.setOrders(orders);

                myReader.close();
            } catch (FileNotFoundException e) {

            }

        } else {
            JOptionPane.showMessageDialog(this, "ID or Password can not be empty!", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }// GEN-LAST:event_loginBtnActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_IDFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pssFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pssFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDField;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginHeadingLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel userIDLabel;
    // End of variables declaration//GEN-END:variables
}
