/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystexm/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class MenuFrame extends javax.swing.JFrame {

    ArrayList<Product> products;
    Customer obj = null;

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame(Customer obj) {

        this.obj = obj;
        initComponents();
        ImageIcon background_img = new ImageIcon(
                "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SMMS_Images\\SMMS_Images\\Menu.png", "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(1300, 750, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 1300, 750);
        this.add(backgrnd);
        this.setTitle("User Menu");
        this.setResizable(false);
        showCartBtn.setOpaque(true);
        categoriesBtn.setOpaque(true);
        showDetailsBtn.setOpaque(true);
        showPrevOrdersBtn.setOpaque(true);
        logoutBtn.setOpaque(true);
        changePasswordBtn.setOpaque(true);
        this.setLocationRelativeTo(null);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setLocation(0, 0);

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriesBtn = new javax.swing.JButton();
        showDetailsBtn = new javax.swing.JButton();
        showCartBtn = new javax.swing.JButton();
        showPrevOrdersBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        changePasswordBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categoriesBtn.setBackground(new java.awt.Color(255, 128, 112));
        categoriesBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        categoriesBtn.setText("Categories");
        categoriesBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        categoriesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        categoriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesBtnActionPerformed(evt);
            }
        });

        showDetailsBtn.setBackground(new java.awt.Color(255, 128, 112));
        showDetailsBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        showDetailsBtn.setText("View Details");
        showDetailsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showDetailsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDetailsBtnActionPerformed(evt);
            }
        });

        showCartBtn.setBackground(new java.awt.Color(255, 128, 112));
        showCartBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        showCartBtn.setText("Cart");
        showCartBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showCartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCartBtnActionPerformed(evt);
            }
        });

        showPrevOrdersBtn.setBackground(new java.awt.Color(255, 128, 112));
        showPrevOrdersBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        showPrevOrdersBtn.setText("View Orders");
        showPrevOrdersBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        showPrevOrdersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPrevOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPrevOrdersBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(255, 128, 112));
        logoutBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        logoutBtn.setText("Log Out");
        logoutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        changePasswordBtn.setBackground(new java.awt.Color(255, 128, 112));
        changePasswordBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        changePasswordBtn.setText("Change Password");
        changePasswordBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        changePasswordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showCartBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriesBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showPrevOrdersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(259, 259, 259))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPrevOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showDetailsBtnActionPerformed
        UserInfoFrame obj1 = new UserInfoFrame(obj);
        obj1.setVisible(true);

    }// GEN-LAST:event_showDetailsBtnActionPerformed

    private void changePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_changePssBtnActionPerformed
        ChangePasswordFrame object = new ChangePasswordFrame(obj);
        object.setVisible(true);

    }// GEN-LAST:event_changePssBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        String info = obj.getID() + "," + obj.getName() + "," + obj.getPassword() + "," + obj.getAddress() + ","
                + obj.getPhoneNumber() + "," + obj.getGender();

        try {
            FileWriter myWriter = new FileWriter(
                    "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                            + obj.getID() + ".txt");

            myWriter.write(info);
            myWriter.close();
            this.setVisible(false);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
        try {
            FileWriter myWriter = new FileWriter(
                    "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                            + obj.getID()
                            + "_orders.txt");
            ArrayList<Order> or = obj.getOrders();
            for (int i = 0; i < or.size(); i++) {
                myWriter.write(or.get(i).toString() + "\n");

            }
            myWriter.close();
            JOptionPane.showMessageDialog(this, "Logged Out Successfully!", "ALERT", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

    }// GEN-LAST:event_logoutBtnActionPerformed

    private void categoriesBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showCatBtnActionPerformed
        String line;

        products = new ArrayList<>();
        File myObj = new File(
                "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\productsDetails.txt");
        Scanner myReader;
        try {
            myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                line = myReader.nextLine();
                String[] res = line.split("[,]", 0);
                if (res[1].equals("EL")) {
                    Product el = new Electronics(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(el);
                } else if (res[1].equals("KA")) {
                    Product ka = new kitchen(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(ka);
                } else if (res[1].equals("Dairy")) {
                    Product dairy = new Dairy(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(dairy);
                } else if (res[1].equals("COS")) {
                    Product cos = new Cosmetics(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(cos);
                } else if (res[1].equals("FG")) {
                    Product fg = new FruitAndVegitables(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(fg);
                } else if (res[1].equals("HE")) {
                    Product he = new Households(Integer.parseInt(res[0]), Integer.parseInt(res[3]),
                            Double.parseDouble(res[4]), res[2], res[1], res[5], res[6]);
                    products.add(he);
                }

            }
            CategoriesFrame object = new CategoriesFrame(obj, products);
            object.setVisible(true);

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

        }

    }// GEN-LAST:event_showCatBtnActionPerformed

    private void showPrevOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showPrevOrdersBtnActionPerformed
        // TODO add your handling code here:
        if (obj.getOrders().isEmpty()) {
            JOptionPane.showMessageDialog(this, "You have NO previous orders!", "ALERT",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {
            PrevOrdersFrame obj1 = new PrevOrdersFrame(obj);
            obj1.setVisible(true);

        }

    }// GEN-LAST:event_showPrevOrdersBtnActionPerformed

    private void showCartBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showCartBtnActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        ArrayList<Order> ors = obj.getOrders();
        for (int j = 0; j < ors.size(); j++) {
            if (ors.get(j).getType().equals("curr")) {
                flag = true;
                break;
            }
        }
        if (!flag) {
            JOptionPane.showMessageDialog(this, "Your Cart is Empty!", "ALERT", JOptionPane.INFORMATION_MESSAGE);

        } else {
            CartFrame obj1 = new CartFrame(obj, products);
            obj1.setVisible(true);
        }

    }// GEN-LAST:event_showCartBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton categoriesBtn;
    private javax.swing.JButton changePasswordBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton showCartBtn;
    private javax.swing.JButton showDetailsBtn;
    private javax.swing.JButton showPrevOrdersBtn;
    // End of variables declaration//GEN-END:variables
}
