
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter; // Import the FileWriter class
import java.io.IOException;
import java.util.Scanner;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class SignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */
    public SignUpFrame() {
        initComponents();
        ImageIcon background_img = new ImageIcon(
                "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SMMS_Images\\SMMS_Images\\signup.png\\", "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(1300, 750, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 1300, 750);
        this.add(backgrnd);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setLocation(0, 0);
        this.setTitle("Sign Up");
        this.setResizable(false);
        panel1.setOpaque(true);
        panel1.setBackground(new Color(0, 0, 0, 90));
        buttonGroup1.add(Male);
        buttonGroup1.add(Female);
        signUpBtn.setOpaque(true);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addField = new javax.swing.JTextField();
        pssField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        signUpBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        signupHeadingLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        panel1.setPreferredSize(new java.awt.Dimension(466, 685));

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setFont(new java.awt.Font("Hubballi", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Full Name");

        nameField.setBackground(new java.awt.Color(204, 204, 204));
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Hubballi", 1, 14)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(255, 255, 255));
        genderLabel.setText("Gender:");

        phoneLabel.setFont(new java.awt.Font("Hubballi", 1, 14)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Phone Number:");

        phoneField.setBackground(new java.awt.Color(204, 204, 204));
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("Hubballi", 1, 14)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(255, 255, 255));
        addressLabel.setText("Your Address:");

        addField.setBackground(new java.awt.Color(204, 204, 204));
        addField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFieldActionPerformed(evt);
            }
        });

        pssField.setBackground(new java.awt.Color(204, 204, 204));
        pssField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssFieldActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Hubballi", 1, 12)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password");

        Female.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Female.setForeground(new java.awt.Color(255, 255, 255));
        Female.setText("Female");

        Male.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Male.setForeground(new java.awt.Color(255, 255, 255));
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        signUpBtn.setBackground(new java.awt.Color(255, 128, 112));
        signUpBtn.setFont(new java.awt.Font("Hoefler Text", 1, 14)); // NOI18N
        signUpBtn.setText("Sign Up");
        signUpBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        signUpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Hubballi", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        signupHeadingLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        signupHeadingLabel.setForeground(new java.awt.Color(255, 255, 255));
        signupHeadingLabel.setText("Sign Up ");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signupHeadingLabel)
                    .addComponent(jLabel6)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(Female)
                            .addGap(110, 110, 110)
                            .addComponent(Male))
                        .addComponent(genderLabel)
                        .addComponent(addressLabel)
                        .addComponent(phoneLabel)
                        .addComponent(nameField)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pssField)
                        .addComponent(phoneField)
                        .addComponent(addField)
                        .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameLabel)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(signupHeadingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pssField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(genderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Male)
                    .addComponent(Female))
                .addGap(27, 27, 27)
                .addComponent(signUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 169, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_nameFieldActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_phoneFieldActionPerformed

    private void addFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_addFieldActionPerformed

    private void pssFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pssFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_pssFieldActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signUpBtnActionPerformed
        if (nameField.getText().length() != 0 && pssField.getText().length() != 0 && addField.getText().length() != 0
            && phoneField.getText().length() != 0) {
        if (!Female.isSelected() && !Male.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please select gender option!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (!isValidName(nameField.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid name (alphabetical characters only)!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (!isValidPhoneNumber(phoneField.getText())) {
            JOptionPane.showMessageDialog(this, "Please enter a valid phone number (e.g., 03xxxxxxxxx)!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
                String data = "";
                try {
                    File myObj = new File(
                            "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\ID_Counter.txt");
                    Scanner myReader = new Scanner(myObj);

                    while (myReader.hasNextLine()) {
                        data = myReader.nextLine();
                    }
                    try {
                        FileWriter myWriter = new FileWriter(
                                "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\"
                                        + data + ".txt");
                        String info = "";
                        if (Male.isSelected()) {
                            info = data + "," + nameField.getText() + "," + pssField.getText() + ","
                                    + addField.getText() + "," + phoneField.getText() + "," + "Male";

                        } else {
                            info = data + "," + nameField.getText() + "," + pssField.getText() + ","
                                    + addField.getText() + "," + phoneField.getText() + "," + "Female";

                        }
                        myWriter.write(info);
                        myWriter.close();
                        JOptionPane.showMessageDialog(this, "User Successfully Registered!\nYour Login ID is: " + data,
                                "ALERT", JOptionPane.INFORMATION_MESSAGE);
                        this.setVisible(false);
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);

                    }
                    myReader.close();

                } catch (FileNotFoundException e) {
                    JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
                int ID = Integer.parseInt(data);
                ID++;
                try {
                    FileWriter myWriter = new FileWriter(
                            "C:\\Users\\MINAHIL SHAKOOR\\Downloads\\Grocery_Management_System_Java\\SuperMarketManagementSystem\\src\\ID_Counter.txt");
                    myWriter.write("" + ID);
                    myWriter.close();
                    this.setVisible(false);
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Application ERROR", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }
        } else {

            JOptionPane.showMessageDialog(this, "Input field can not be empty!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_signUpBtnActionPerformed
    
    private boolean isValidName(String name) {
    // Check if the name contains only alphabetic characters and spaces
    return name.matches("^[a-zA-Z\\s]+$");
}

private boolean isValidPhoneNumber(String phoneNumber) {
    // Check if the phone number has the format 03xxxxxxxxx
    return phoneNumber.matches("^03\\d{9}$");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Female;
    private javax.swing.JRadioButton Male;
    private javax.swing.JTextField addField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel panel1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPasswordField pssField;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JLabel signupHeadingLabel;
    // End of variables declaration//GEN-END:variables
}
